otoshimono/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('otoshimonoapp.urls')),
    path('admin/', admin.site.urls),
]

otoshimonoapp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'otoshimonoapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:otoshimono_id>/', views.detail, name='detail'),
    path('about/', views.about, name="about"),
    path('form/', views.form, name="form"),
    path('list/', views.listing, name="list"),
    path('add/', views.add, name="add"),
    path('form/location/', views.form_location, name="form_location"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

otoshimonoapp/models.py
from django.db import models


class OtoshimonoInfo(models.Model):
    obj_name = models.CharField(max_length=200)
    place_found = models.CharField(max_length=200, default="")
    place_now = models.CharField(max_length=200, default="見つけた場所と同じ")
    pub_date = models.DateTimeField('date published')
    location = models.CharField(max_length=200, default="")
    image = models.ImageField(upload_to='otoshimono/', default='otoshimono/no_image.jpg')

    def __str__(self):
        return self.obj_name

otoshimonoapp/forms.py
from django import forms

from otoshimonoapp.models import OtoshimonoInfo


class OtoshimonoRegisterForm(forms.ModelForm):
    """"落とし物登録画面のフォーム"""
    limit_image_size = 10 * 1024 * 1024

    class Meta:
        model = OtoshimonoInfo
        fields = ['obj_name', 'place_found', 'place_now', 'location', 'image']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def clean_obj_name(self):
        obj_name = self.cleaned_data["obj_name"]
        if len(obj_name) > 200:
            raise forms.ValidationError(
                '200文字以内で入力してください。',
            )
        return obj_name

    def clean_image(self):
        image = self.cleaned_data["image"]
        if image is not None:
            if image.size > self.limit_image_size:
                raise forms.ValidationError(
                    '画像は10MB以下のものをアップロードしてください',
                )
        return image

otoshimonoapp/views.py
import json
import uuid
from datetime import date, datetime

from django.contrib import messages
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from otoshimonoapp.forms import OtoshimonoRegisterForm

from .models import OtoshimonoInfo

# json.dumpでJSON型に変換できない型の例外処理


def convertDataToJson(object):
    if isinstance(object, (datetime, date)):
        return object.isoformat()
    elif (isinstance(object, uuid.UUID)):
        return str(object)


def index(request):
    latest_otoshimono_list = OtoshimonoInfo.objects.order_by('-pub_date')[:100]
    context = {
        'latest_otoshimono_list': json.dumps(list(latest_otoshimono_list.values()),
                                             ensure_ascii=False,
                                             default=convertDataToJson),
        'image_url_list': json.dumps([item.image.url for item in latest_otoshimono_list],
                                     ensure_ascii=False,
                                     default=convertDataToJson)
    }
    return render(request, 'otoshimonoapp/index.html', context)


def detail(request, otoshimono_id):
    otoshimono = get_object_or_404(OtoshimonoInfo, pk=otoshimono_id)
    return render(request, 'otoshimonoapp/detail.html', {'otoshimono': otoshimono})


def about(request):
    context = {}
    return render(request, 'otoshimonoapp/about.html', context)


def listing(request):
    latest_otoshimono_list = OtoshimonoInfo.objects.order_by('-pub_date')[:100]
    context = {'latest_otoshimono_list': latest_otoshimono_list}
    return render(request, 'otoshimonoapp/list.html', context)


def form(request):
    context = {}
    return render(request, 'otoshimonoapp/form.html', context)


def form_location(request):
    context = {}
    return render(request, 'otoshimonoapp/form_location.html', context)


def add(request):
    form = OtoshimonoRegisterForm(request.POST, request.FILES)
    is_valid = form.is_valid()
    if not is_valid:
        return render(request, 'otoshimonoapp/form.html', {'form': form})

    otoshimono = form.save(commit=False)
    otoshimono.pub_date = timezone.now()
    otoshimono.save()

    messages.info(request, f"「{otoshimono.obj_name}」 が追加されました。ご報告ありがとうございます。")
    context = {}
    return render(request, 'otoshimonoapp/form.html', context)

otoshimonoapp/templates/otoshimonoapp/about.html
{% extends 'otoshimonoapp/base.html' %}

{% block title %}About{% endblock %}

{% block contents %}
<p class="text-center p-3">おとしもの共有SNSです</p>
{% endblock %}

otoshimonoapp/templates/otoshimonoapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="icon" href="{% static "img/favicon.ico" %}">
    <title>{% block title %}{% endblock %}</title>
  </head>
  
  <body class="d-flex flex-column" style="min-height: 100vh">
    <header class="sticky-top">
      {% include "otoshimonoapp/header.html" %}
    </header>
    {% block contents %}{% endblock %}

    {% include "otoshimonoapp/footer.html" %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

otoshimonoapp/templates/otoshimonoapp/detail.html
{% extends 'otoshimonoapp/base.html' %}

{% block contents %}
<div class="m-1">
    <img src="{{ otoshimono.image.url }}" class="mb-1 mw-100" alt="ないよ">
    <div class="p-2">
        <h1>{{ otoshimono.obj_name }}</h1>
        <div class="date">
            {{ otoshimono.pub_date }}
        </div>
        <div class="place_found">
            {{ otoshimono.place_found }}
        </div>
    </div>
    <div class="px-2 mb-3" style="overflow: auto">
        <button class="btn btn-primary mx-1" onclick="history.back(-1)" style="float: right">戻る</button>
        <button type="button" class="btn btn-primary mx-1" style="float: right">見つかった</button>
    </div>
</div>
{% endblock %}

otoshimonoapp/templates/otoshimonoapp/footer.html
{% load static %}

<footer class="mb-1 mt-auto py-3 text-muted text-center text-small">
       © 2021 落とし物共有SNS
</footer>

otoshimonoapp/templates/otoshimonoapp/form.html
{% extends 'otoshimonoapp/base.html' %}

{% block title %}おとしもの情報投稿{% endblock %}

{% block contents %}
<div class='container'>
    <p>おとしもの情報投稿</p>
    <form action="{% url 'otoshimonoapp:add' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset>
            <div class="mb-3">
                <label for="obj_name" class="form-label">おとしものの名前</label>
                <input type="text" name="obj_name" class="form-control" id="title" required>
            </div>
            <div class="mb-3">
                <label for="place_found" class="form-label">見つけた場所</label>
                <input type="text" name="place_found" class="form-control" id="place_found" required>
            </div>
            <div class="mb-3">
                <button type="button" class="btn btn-primary" onclick="getLocation()">現在地を追加</button>
                <button type="button" class="btn btn-primary" onclick="redirect('{% url 'otoshimonoapp:form_location' %}')">地図から位置情報を追加</button>
                <label class="mx-3" id="location_result">位置情報が追加されていません。</label>
                <input type="text" class="d-transparent" name="location" id="location_input" required>
            </div>
            <div class="mb-3">
                <label for="place_now" class="form-label">届け先</label>
                <input type="text" name="place_now" class="form-control" id="place_now" value="見つけた場所と同じ">
            </div>
            <div class="mb-3">
                <label for="place_now" class="form-label">落とし物画像</label>
                <input type="file" name="image" class="form-control" id="image" accept="image/*">
            </div>
        </fieldset>
        <div class='p-3' style="overflow: auto">
            <button type="submit" class="btn btn-primary" style="float: right" onclick="sessionStorage.clear()">Submit</button>
        </div>
        {% for message in messages %}
        <div>
            <label>{{ message }}</label>
        </div>
        {% endfor %}
    </form>
</div>

<script src="https://maps.google.com/maps/api/js?key={{ GMAP_APIKEY }}&language=ja"></script>
<script>
var output = document.getElementById("location_result");
var form_elements = ['title', 'place_found', 'place_now', 'image'];
function getLocation() {  
  if (!navigator.geolocation){//Geolocation apiがサポートされていない場合
    output.innerHTML = "<p>Geolocationはあなたのブラウザーでサポートされておりません</p>";
    return;
  }
  function success(position) {
    var latitude  = position.coords.latitude;//緯度
    var longitude = position.coords.longitude;//経度
    output.innerHTML = '位置情報が追加されました。' + '緯度: ' + latitude + '°, 経度: ' + longitude + '°';
    // 位置情報
    var latlng = new google.maps.LatLng( latitude , longitude );
    var button = document.getElementById("location_input");
    button.value = JSON.stringify(latlng);
  };
  function error() {
    //エラーの場合
    output.innerHTML = "位置情報を取得できません";
  };
  output.innerHTML = "位置情報を取得中です。"
  navigator.geolocation.getCurrentPosition(success, error);//成功と失敗を判断
}
function redirect(path) {
  form_elements.forEach((el) => {
    var v = document.getElementById(el).value;
    sessionStorage.setItem(el, v);
  })
  window.location.href = path;
}

window.onload = function() {
  form_elements.forEach((el) => {
    try {
      var v = sessionStorage.getItem(el);
      document.getElementById(el).value = v;
    } catch(error) {
      return;
    }
  })
};

var queryString = window.location.search;
var queryObject = new Object();
if(queryString){
  queryString = queryString.substring(1);
  var parameters = queryString.split('&');

  for (var i = 0; i < parameters.length; i++) {
    var element = parameters[i].split('=');

    var paramName = decodeURIComponent(element[0]);
    var paramValue = decodeURIComponent(element[1]);

    queryObject[paramName] = paramValue;
  }
}
if ("lat" in queryObject && "lng" in queryObject) {
    var latitude = Number(queryObject.lat);
    var longitude = Number(queryObject.lng);
    output.innerHTML = '位置情報が追加されました。' + '緯度: ' + latitude + '°, 経度: ' + longitude + '°';
    var latlng = new google.maps.LatLng( latitude , longitude );
    var button = document.getElementById("location_input");
    button.value = JSON.stringify(latlng);
}
</script>

<style>
.d-transparent {
  opacity: 0;
  width: 0px;
}
</style>
{% endblock %}

otoshimonoapp/templates/otoshimonoapp/form_location.html
{% extends 'otoshimonoapp/base.html' %}
{% load static %}
{% block contents %}
<div class="p-1">
    <button class="btn btn-primary" onclick="getMyPlace()">現在位置に移動</button>
    <label class="py-1 px-3" id="result"></label>
    <button class="btn btn-primary" onclick="passLocationData()">位置情報を入力</button>
</div>
<div id="map"></div>
<script src="https://maps.google.com/maps/api/js?key={{ GMAP_APIKEY }}&language=ja"></script>
<script>
// ロード時に位置情報を取得する
// 成功時: 現在位置を中心に地図を表示
// 失敗時: 東京駅を中心に地図を表示

// DOM関係
var output = document.getElementById("result");

async function getMyPlace() {
  if (!navigator.geolocation){//Geolocation apiがサポートされていない場合
    output.innerHTML = "Geolocationはあなたのブラウザーでサポートされておりません";
    return;
  }
  function success(position) {
    var latitude  = position.coords.latitude;//緯度
    var longitude = position.coords.longitude;//経度
    output.innerHTML = '緯度 ' + latitude + '°,  経度 ' + longitude + '°';
    // 位置情報
    var latlng = new google.maps.LatLng( latitude , longitude );
    // Google Mapsに書き出し
    map.setCenter(latlng);
  };
  function error() {
    //エラーの場合
    output.innerHTML = "座標位置を取得できません";
  };
  navigator.geolocation.getCurrentPosition(success, error);//成功と失敗を判断
}
function passLocationData() {
    var center = map.getCenter();
    var uri = encodeURI("{% url 'otoshimonoapp:form' %}?lat="+center.lat()+"&lng="+center.lng());
    location.href = uri;
}

function parseAddress() {
    geocoder.geocode(
        {
            'latLng': map.getCenter(),
        },
        function(results, status){
            if(status==google.maps.GeocoderStatus.OK){
                var output = document.getElementById("result");
                output.innerHTML = results[0].formatted_address.replace(/^日本, /, '');
            }
        }
    );
}

var initial_centor = new google.maps.LatLng(35.6811673, 139.7670516);
var Options = {
 zoom: 15,      //地図の縮尺値
 center: initial_centor,    //地図の中心座標
 mapTypeId: 'roadmap'   //地図の種類
};
var map = new google.maps.Map(document.getElementById('map'), Options)
console.log(map);
var geocoder = new google.maps.Geocoder();
map.addListener('center_changed', () => {
    parseAddress();
});

function parseAddress() {
    geocoder.geocode(
        {
            'latLng': map.getCenter(),
        },
        function(results, status){
            if(status==google.maps.GeocoderStatus.OK){
                var output = document.getElementById("result");
                output.innerHTML = results[0].formatted_address.replace(/^日本, /, '');
            }
        }
    );
}
</script>

<!-- Google Map -->
<style>
html { height: 100% }
body { height: 100% }
#map { height: 100%; width: 100%}


body, html, #map { height: 100%; margin: 0 }
#map {
    position: relative;
}

#map:after {
    width: 22px;
    height: 40px;
    display: block;
    content: ' ';
    position: absolute;
    top: 50%; left: 50%;
    margin: -40px 0 0 -11px;
    background: url('{% static "otoshimonoapp/img/map_pin.png" %}');
    background-size: 22px 40px; /* Since I used the HiDPI marker version this compensates for the 2x size */
    pointer-events: none; /* This disables clicks on the marker. Not fully supported by all major browsers, though */
}
</style>
{% endblock %}

otoshimonoapp/templates/otoshimonoapp/header.html
{% load static %}

<div class="container-fluid px-0">
  <header class="d-flex justify-content-center pt-3 pb-2 bg-white">
    <ul class="nav nav-pills" id="pills-tab" role="tablist">
      <li class="nav-item"><a href="{% url 'otoshimonoapp:index' %}" id="nav-index" class="nav-link" data-bs-toggle="pills" role="tab" aria-selected="true">Home</a></li>
      <li class="nav-item"><a href="{% url 'otoshimonoapp:list' %}" id="nav-list" class="nav-link" data-bs-toggle="pills" role="tab" aria-selected="false">List</a></li>
      <li class="nav-item"><a href="{% url 'otoshimonoapp:form' %}" id="nav-form" class="nav-link" data-bs-toggle="pills" role="tab" aria-selected="false">Add</a></li>
      <li class="nav-item"><a href="{% url 'otoshimonoapp:about' %}" id="nav-about" class="nav-link" data-bs-toggle="pills" role="tab" aria-selected="false">About</a></li> 
    </ul>
  </header>
</div>

<script>
  var url = window.location.href;
  if (url.match("/list/")) {
    $("#nav-list").addClass("active");
  } else if (url.match("/form/")) {
    $("#nav-form").addClass("active");
  } else if (url.match("/about/")) {
    $("#nav-about").addClass("active");
  } else {
    $("#nav-index").addClass("active");
  }
</script>

otoshimonoapp/templates/otoshimonoapp/index.html
{% extends 'otoshimonoapp/base.html' %}

{% block contents %}
<div class="p-1">
    <button class="btn btn-primary" onclick="getMyPlace()">現在位置を取得</button>
    <label class="py-1 px-3" id="result"></label>
</div>
<div id="map"></div>
<script src="https://maps.google.com/maps/api/js?key={{ GMAP_APIKEY }}&language=ja"></script>
<script>
function getMyPlace() {
  var output = document.getElementById("result");
  if (!navigator.geolocation){//Geolocation apiがサポートされていない場合
    output.innerHTML = "Geolocationはあなたのブラウザーでサポートされておりません";
    return;
  }
  function success(position) {
    var latitude  = position.coords.latitude;//緯度
    var longitude = position.coords.longitude;//経度
    output.innerHTML = '緯度 ' + latitude + '°,  経度 ' + longitude + '°';
    // 位置情報
    var latlng = new google.maps.LatLng( latitude , longitude );
    // Google Mapsに書き出し
    map.setCenter(latlng);
  };
  function error() {
    //エラーの場合
    output.innerHTML = "座標位置を取得できません";
  };
  navigator.geolocation.getCurrentPosition(success, error);//成功と失敗を判断
}

var Options = {
 zoom: 15,      //地図の縮尺値
 center: new google.maps.LatLng(35.6811673, 139.7670516),    //地図の中心座標
 mapTypeId: 'roadmap'   //地図の種類
};
var map = new google.maps.Map(document.getElementById('map'), Options);

var latest_otoshimono_list = JSON.parse("{{ latest_otoshimono_list|escapejs }}");
var image_url_list = JSON.parse("{{ image_url_list|escapejs }}");
latest_otoshimono_list.forEach((otoshimono, i) => {
    try {
        var latlng = JSON.parse(otoshimono.location);
    } catch (error) {
        return;
    }
    const marker = new google.maps.Marker({
        map: map,
        position: latlng,
    });
    const infowindow = new google.maps.InfoWindow({
    content: '<img src='+image_url_list[i]+' alt="error" style="width: 100px"><br>'+otoshimono.obj_name
    });
    infowindow.set("isOpen", false);
    marker.addListener("mouseover", () => {
        infowindow.open(map, marker);
    });
    marker.addListener("mouseout", () => {
        if (!infowindow.get("isOpen")) {
            infowindow.close();
        } 
    });
    marker.addListener("click", () => {
        if (infowindow.get("isOpen")) {
            infowindow.close();
            infowindow.set("isOpen", false);
        } else {
            infowindow.open(map, marker);
            infowindow.set("isOpen", true);
        }
    });
    infowindow.addListener("closeclick", () => {
        infowindow.close();
        infowindow.set("isOpen", false);
    });
});
</script>

<!-- Google Map -->
<style>
html { height: 100% }
body { height: 100% }
#map { height: 100%; width: 100%}
</style>
{% endblock %}

otoshimonoapp/templates/otoshimonoapp/list.html
{% extends 'otoshimonoapp/base.html' %}

{% block title %}おとしもの一覧{% endblock %}

{% block contents %}
    <style>
        @media (max-width: 576px) {
            div.card-group {
                display: flex;
                flex-direction: column;
                align-items: center;
            }
        }
    </style>
    {% if latest_otoshimono_list %}
        <div class="card-group p-3">
        {% for otoshimono in latest_otoshimono_list %}
            <div class="card m-1 border border-2 rounded-3" style="width: 18rem; max-width: 18rem; min-width: 12rem">
                <div class="overflow-hidden rounded d-flex align-items-center justify-content-center" style="height: 45%">
                    <img src="{{ otoshimono.image.url }}" class="img-fluid" alt="ないよ" style="max-height: 100%">
                </div>
                <div class="card-body">
                <h5 class="card-title">{{ otoshimono.obj_name }}</h5>
                <p class="card-text">{{otoshimono.place_found}}</p>
                <a href="{% url 'otoshimonoapp:detail' otoshimono.id %}" class="btn btn-primary" style="float: right">詳しくみる</a>
            </div>
        </div>
        {% endfor %}
        </div>
    {% else %}
        <p>落とし物はありません</p>
    {% endif %}

{% endblock %}